version: 2

run:
  timeout: 5m

issues:
  exclude-use-default: false

linters:
  default: none
  enable:
    - govet
    - staticcheck

linters-settings:
  staticcheck:
    checks:
      - "all"
      - "-U1000"
      - "-SA4006"
      - "-QF1001"
      - "-QF1012"